### ISSUE TITLE
对tidb的fuzz有没有什么发现？

### ISSUE THREAD

**Issue by leveryd** [s3nt3/sqlvine#1]
因为我也打算fuzz tidb，所以想问一下你们的进展。

**Comment by s3nt3** [comment]
欢迎师傅来尝试啊，由于 golang 下传统的二进制漏洞无法利用，只能作为 bug，所以 fuzz 的工作暂时没有继续推进，我之前挖漏洞还是以代码审计为主。

**Comment by leveryd** [comment]
安排上
